name: Server workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  QT5: 5.15.2
  QT6: 6.2.1
  VULKAN_VER: 1.2.189
  VULKAN_VER_FULL: 1.2.189.0

jobs:
  ubuntu-jobs-generator:
    runs-on: ubuntu-latest
    outputs:
      job-matrix: ${{ steps.set-matrix.outputs.job-matrix }}
    steps:
      - id: set-matrix
        run: echo "::set-output name=job-matrix::{\"os\":[\"ubuntu\"],\"qt\":[\"${{ env.QT5 }}\",\"${{ env.QT6 }}\"]}"

  win-mac-generator:
    runs-on: ubuntu-latest
    outputs:
      job-matrix: ${{ steps.set-matrix.outputs.job-matrix }}
    steps:
      - id: set-matrix
        run: echo "::set-output name=job-matrix::{\"os\":[\"windows\",\"macos\"],\"qt\":[\"${{ env.QT5 }}\",\"${{ env.QT6 }}\"]}"

  ubuntu-test:
    needs: [ubuntu-jobs-generator]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.ubuntu-jobs-generator.outputs.job-matrix)}}
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ matrix.os }}-QtCache-${{ matrix.qt }}
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          aqtversion: ==2.0.0
          modules: ${{ matrix.qt == env.QT6 && 'qtwebsockets' || '' }}
          version: '${{ matrix.qt }}'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          submodules: 'recursive'

      - name: Set outputs
        run: |
          echo "::set-output name=dependencies::$(python3 ${{ github.workspace }}/scripts/vcpkgPackages.py qt${{ matrix.qt }} ${{ matrix.os }}-latest)"
          echo "::set-output name=cacheKey::$(python3 ${{ github.workspace }}/scripts/vcpkgCacheKey.py qt${{ matrix.qt }} ${{ matrix.os }}-latest)."
          echo "::set-output name=triplet::x64-$(python3 ${{ github.workspace }}/scripts/triplet.py ${{ matrix.os }})"
          echo "::set-output name=cc::$(python3 ${{ github.workspace }}/scripts/cc.py ${{ matrix.os }})"
          echo "::set-output name=cxx::$(python3 ${{ github.workspace }}/scripts/cxx.py ${{ matrix.os }})"
        id: set-outputs
        env:
          PYTHONPATH: ./QtPiDeckCommon/scripts/

      - name: Check outputs
        run: |
          echo "dependencies=${{ steps.set-outputs.outputs.dependencies }}"
          echo "cacheKey=${{ steps.set-outputs.outputs.cacheKey }}"
          echo "triplet=${{ steps.set-outputs.outputs.triplet }}"
          echo "cc=${{ steps.set-outputs.outputs.cc }}"
          echo "cxx=${{ steps.set-outputs.outputs.cxx }}"

      - uses: lukka/run-vcpkg@v7.3
        with:
          vcpkgDirectory: ${{ github.workspace }}/QtPiDeckCommon/ext/vcpkg
          appendedCacheKey: ${{ steps.set-outputs.outputs.cacheKey }}
          vcpkgTriplet: ${{ steps.set-outputs.outputs.triplet }}
          vcpkgArguments: ${{ steps.set-outputs.outputs.dependencies }}
          doNotUpdateVcpkg: true
        if: steps.vcpkgPackages.outputs.dependencies != 'nil'

      - name: Install additional Qt6 dependencies
        run: |
          wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-${VULKAN_VER}-focal.list https://packages.lunarg.com/vulkan/${VULKAN_VER}/lunarg-vulkan-${VULKAN_VER}-focal.list
          sudo apt update
          sudo apt install
          sudo apt install vulkan-sdk libxkbcommon-dev -y
        if: matrix.os == 'ubuntu' && matrix.qt == env.QT6

      - uses: lukka/get-cmake@latest

      - name: Create build directory
        run: cmake -E make_directory "build"

      - run: cmake -S . -B build -G Ninja -DBUILD_COMMON_TESTS=OFF -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/QtPiDeckCommon/ext/vcpkg/scripts/buildsystems/vcpkg.cmake
        env:
          CC: ${{ steps.set-outputs.outputs.cc }}
          CXX: ${{ steps.set-outputs.outputs.cxx }}

      - run: cmake --build build

      - name: Test project
        run: ctest --output-on-failure
        working-directory: build
        env:
          LD_LIBRARY_PATH: ./QtPiDeckCommon/QtPiDeckCommon

  win-mac-test:
    needs: [win-mac-generator]
    runs-on: ${{ format('{0}-latest', matrix.os) }}
    strategy:
      matrix: ${{fromJSON(needs.win-mac-generator.outputs.job-matrix)}}
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ matrix.os }}-QtCache-${{ matrix.qt }}
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          aqtversion: ==2.0.0
          modules: ${{ matrix.qt == env.QT6 && 'qtwebsockets' || '' }}
          version: '${{ matrix.qt }}'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          submodules: 'recursive'

      - name: Set outputs
        run: |
          echo "::set-output name=dependencies::$(python3 ${{ github.workspace }}/scripts/vcpkgPackages.py qt${{ matrix.qt }} ${{ matrix.os }}-latest)"
          echo "::set-output name=cacheKey::$(python3 ${{ github.workspace }}/scripts/vcpkgCacheKey.py qt${{ matrix.qt }} ${{ matrix.os }}-latest)."
          echo "::set-output name=triplet::x64-$(python3 ${{ github.workspace }}/scripts/triplet.py ${{ matrix.os }})"
          echo "::set-output name=cc::$(python3 ${{ github.workspace }}/scripts/cc.py ${{ matrix.os }})"
          echo "::set-output name=cxx::$(python3 ${{ github.workspace }}/scripts/cxx.py ${{ matrix.os }})"
        id: set-outputs
        env:
          PYTHONPATH: ./QtPiDeckCommon/scripts/

      - name: Check outputs
        run: |
          echo "dependencies=${{ steps.set-outputs.outputs.dependencies }}"
          echo "cacheKey=${{ steps.set-outputs.outputs.cacheKey }}"
          echo "triplet=${{ steps.set-outputs.outputs.triplet }}"
          echo "cc=${{ steps.set-outputs.outputs.cc }}"
          echo "cxx=${{ steps.set-outputs.outputs.cxx }}"

      - uses: lukka/run-vcpkg@v7.3
        with:
          vcpkgDirectory: ${{ github.workspace }}/QtPiDeckCommon/ext/vcpkg
          appendedCacheKey: ${{ steps.set-outputs.outputs.cacheKey }}
          vcpkgTriplet: ${{ steps.set-outputs.outputs.triplet }}
          vcpkgArguments: ${{ steps.set-outputs.outputs.dependencies }}
          doNotUpdateVcpkg: true
        if: steps.vcpkgPackages.outputs.dependencies != 'nil'

      - name: Update llvm-clang
        run: |
          brew update
          brew upgrade llvm
        if: matrix.os == 'macos'

      - name: Cache Vulkan
        id: cache-vulkan
        uses: actions/cache@v1
        with:
          path: C:\VulkanSDK\${{ env.VULKAN_VER_FULL }}
          key: vulkan-${{ env.VULKAN_VER_FULL }}
        if: matrix.os == 'windows' && matrix.qt == env.QT6

      - name: Setup Vulkan(windows)
        run: |
           Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/${env:VULKAN_VER_FULL}/windows/VulkanSDK-${env:VULKAN_VER_FULL}-Installer.exe" -OutFile VulkanSDK.exe
           $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
           $installer.WaitForExit();
        if: matrix.os == 'windows' && matrix.qt == env.QT6 && !steps.cache-vulkan.outputs.cache-hit

      - name: Set vulkan sdk variable(windows)
        run: echo "VULKAN_SDK=C:\VulkanSDK\${env:VULKAN_VER_FULL}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        if: matrix.os == 'windows' && matrix.qt == env.QT6

      - uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows'

      - uses: lukka/get-cmake@latest

      - name: Create build directory
        run: cmake -E make_directory "build"

      - run: cmake -S . -B build -G Ninja -DBUILD_COMMON_TESTS=OFF -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/QtPiDeckCommon/ext/vcpkg/scripts/buildsystems/vcpkg.cmake
        env:
          CC: ${{ steps.set-outputs.outputs.cc }}
          CXX: ${{ steps.set-outputs.outputs.cxx }}

      - run: cmake --build build

      - name: Set path to QtPiDeckCommon library
        run: Get-Location | % { echo "$_\QtPiDeckCommon\QtPiDeckCommon" } | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        working-directory: build
        if: matrix.os == 'windows'

      - name: Test project
        run: ctest --output-on-failure
        working-directory: build
        env:
          LD_LIBRARY_PATH: ./QtPiDeckCommon/QtPiDeckCommon