name: Server workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  QT5: 5.15.2
  QT6: 6.1.1

jobs:
  generator:
    runs-on: ubuntu-latest
    outputs:
      job-matrix: ${{ steps.set-matrix.outputs.job-matrix }}
    steps:
      - id: set-matrix
        run: echo "::set-output name=job-matrix::{\"os\":[\"ubuntu\",\"windows\",\"macos\"],\"qt\":[\"${{ env.QT5 }}\",\"${{ env.QT6 }}\"]}"
  test:
    needs: [generator]
    runs-on: ${{ format('{0}-latest', matrix.os) }}
    strategy:
      matrix: ${{fromJSON(needs.generator.outputs.job-matrix)}}
    steps:
      - run: echo 'Hello ${{ matrix.os }} with Qt ${{ matrix.qt }}'

  clang-tidy:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - run: echo "clang-tidy"

  code-coverage:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - run: echo "code-coverage"